### ISSUE TITLE
How to install netcdf with ifort?

### ISSUE THREAD

**Issue by daye222** [dongli/starman#10]
董老师好
ifort的路径不在/usr/bin/, starman自动检测不到ifort编译器
ifort实际在/opt/intel/compilers_and_libraries_2020.2.254/linux/bin/intel64/这个路径下，
所以我将这个路径添加在了conf.yml 里面（如下所示），但是最后安装的netcdf只有netcdf@4.7.2 netcdf-c@4.7.2 netcdf-fortran@4.5.2；ifort版的netcdf并没有安装，也就是说忽略了我添加的语句。
这种情况，我该怎么办呢？

“defaults:
compiler_set: gcc_8.3.1
compiler_sets:
gcc_8.3.1:
c: "/usr/bin/gcc"
cxx: "/usr/bin/g++"
fortran: "/usr/bin/gfortran"
ifortran: "/opt/intel/compilers_and_libraries_2020.2.254/linux/bin/intel64/ifort"
”

**Comment by dongli** [comment]
应该这样写：
```
defaults:
  compiler_set: intel_2020.2.254
compiler_sets:
  intel_2020.2.254:
    c: /opt/intel/compilers_and_libraries_2020.2.254/linux/bin/intel64/icc
    cxx: /opt/intel/compilers_and_libraries_2020.2.254/linux/bin/intel64/icpc
    fortran: /opt/intel/compilers_and_libraries_2020.2.254/linux/bin/intel64/ifort
```
